config/routes.rb
Rails.application.routes.draw do
  resources :drugs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/drug.rb
class Drug < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/drugs_controller.rb
class DrugsController < ApplicationController
  before_action :set_drug, only: [:show, :edit, :update, :destroy]

  # GET /drugs
  # GET /drugs.json
  def index
    @drugs = Drug.all
  end

  # GET /drugs/1
  # GET /drugs/1.json
  def show
  end

  # GET /drugs/new
  def new
    @drug = Drug.new
  end

  # GET /drugs/1/edit
  def edit
  end

  # POST /drugs
  # POST /drugs.json
  def create
    @drug = Drug.new(drug_params)

    respond_to do |format|
      if @drug.save
        format.html { redirect_to @drug, notice: 'Drug was successfully created.' }
        format.json { render :show, status: :created, location: @drug }
      else
        format.html { render :new }
        format.json { render json: @drug.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /drugs/1
  # PATCH/PUT /drugs/1.json
  def update
    respond_to do |format|
      if @drug.update(drug_params)
        format.html { redirect_to @drug, notice: 'Drug was successfully updated.' }
        format.json { render :show, status: :ok, location: @drug }
      else
        format.html { render :edit }
        format.json { render json: @drug.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /drugs/1
  # DELETE /drugs/1.json
  def destroy
    @drug.destroy
    respond_to do |format|
      format.html { redirect_to drugs_url, notice: 'Drug was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_drug
      @drug = Drug.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def drug_params
      params.require(:drug).permit(:name, :effect, :color, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/drugs_helper.rb
module DrugsHelper
end

app/views/drugs/_form.html.erb
<%= form_with(model: drug, local: true) do |form| %>
  <% if drug.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(drug.errors.count, "error") %> prohibited this drug from being saved:</h2>

      <ul>
      <% drug.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :effect %>
    <%= form.text_field :effect %>
  </div>

  <div class="field">
    <%= form.label :color %>
    <%= form.text_field :color %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/drugs/edit.html.erb
<h1>Editing Drug</h1>

<%= render 'form', drug: @drug %>

<%= link_to 'Show', @drug %> |
<%= link_to 'Back', drugs_path %>

app/views/drugs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Drugs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Effect</th>
      <th>Color</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @drugs.each do |drug| %>
      <tr>
        <td><%= drug.name %></td>
        <td><%= drug.effect %></td>
        <td><%= drug.color %></td>
        <td><%= drug.price %></td>
        <td><%= link_to 'Show', drug %></td>
        <td><%= link_to 'Edit', edit_drug_path(drug) %></td>
        <td><%= link_to 'Destroy', drug, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Drug', new_drug_path %>

app/views/drugs/new.html.erb
<h1>New Drug</h1>

<%= render 'form', drug: @drug %>

<%= link_to 'Back', drugs_path %>

app/views/drugs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @drug.name %>
</p>

<p>
  <strong>Effect:</strong>
  <%= @drug.effect %>
</p>

<p>
  <strong>Color:</strong>
  <%= @drug.color %>
</p>

<p>
  <strong>Price:</strong>
  <%= @drug.price %>
</p>

<%= link_to 'Edit', edit_drug_path(@drug) %> |
<%= link_to 'Back', drugs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Li8</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>